name: Deploy Supabase Edge Function

on:
  push:
    branches: [main]
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install supabase

      - name: Deploy Edge Function
        run: |
          supabase functions deploy hello-world \
            --project-ref $PROJECT_REF \
            --access-token $SUPABASE_ACCESS_TOKEN
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.PROJECT_REF }}
