name: Deploy Supabase Edge Function

on:
  push:
    branches: [main]
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Edge Function
        run: |
          npx supabase link --project-ref ${{ secrets.PROJECT_REF }}
          npx supabase functions deploy hello-world --project-ref ${{ secrets.PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_SUPABASE }}
